### ISSUE TITLE
Not pip installable

### ISSUE THREAD

**Issue by kseistrup** [ivanov/bipython#5]
``` sh
$ sudo pip2.7 install --upgrade bipython
Downloading/unpacking bipython
  Could not find any downloads that satisfy the requirement bipython
[…]
$ sudo pip3.3 install --upgrade bipython
Downloading/unpacking bipython
  Could not find any downloads that satisfy the requirement bipython
[…]
```

**Comment by ivanov** [comment]
try again, I was having some technical difficulties that #3 helped resolve.

**Comment by mattjj** [comment]
It pip installs for me (on OS X and Ubuntu).

**Comment by kseistrup** [comment]
It pip installs fine here now.

**Comment by ivanov** [comment]
@kseistrup - you were like Icarus, flying too close to the sun - burnt by the heat of the initial release, with the PyPI bits still scorching. To commemorate your bravery, I now award you :cake: for opening this issue, so that others would know that they need not be afraid. 

To give us closure on this matter, I will now, by fiat, turn this issue's label from a venerable forrest green to a crimson and let it rest. It will doubtless stay here, gathering dust, as we part ways with it and continue on our journey across the sands of time. But we will never forget. We must never forget issue #5.

**Comment by kseistrup** [comment]
:)
